selector:
  - textarea.tinymce
plugins:
  - advlist
  - autolink
  - lists
  - link
  - image
  - charmap
  - print
  - preview
  - hr
  - anchor
  - pagebreak
  - searchreplace
  - wordcount
  - visualblocks
  - visualchars
  - code
  - fullscreen
  - insertdatetime
  - media
  - nonbreaking
  - save
  - table
  - contextmenu
  - directionality
  - emoticons
  - template
  - paste
  - textcolor
  - colorpicker
  - textpattern
  - imagetools
  - uploadimage
toolbar1: insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image uploadimage
toolbar2: print preview media | forecolor backcolor emoticons
image_advtab: true
plugin_preview_width: 969
content_css:
  - //www.tinymce.com/css/codepen.min.css
uploadimage_form_url:
  - /admin/admin_user_attachments
